### ISSUE TITLE
BoneLibUpdater does not replace invalid installations of BoneLib

### ISSUE THREAD

**Issue by spellboundtriangle** [yowchap/BoneLib#89]
Include the following info or it won't be looked into.
Store (Steam, Oculus): Oculus
Headset (Index, Quest 2, etc): N/A
A detailed description of the issue: When BoneLib.dll is invalid, the updater does not attempt to replace it with a fresh version. The user is then perpetually left with a non-functional BoneLib, even though BoneLibUpdater could have just replaced it.
Steps to recreate the issue: Have an invalid copy of BoneLib.dll in your mods folder and launch the game

Log of this occurring (not mine):
[24-11-23_12-11-49.log](https://github.com/user-attachments/files/17893319/24-11-23_12-11-49.log)

**Comment by spellboundtriangle** [comment]
> The updater pulls from the GitHub releases section, and compares the metadata there with the installed version to check for any differences. If the release is out-of-sync, it will keep downloading and installing the wrong version forever.

I understand that, but based on the log it never reached the point of even reading the version. That was my concern, that it's not even trying to download after it failed to read the existing dll in the first place. This isn't the typical behavior.
As seen [on a Discord help thread](https://discord.com/channels/563139253542846474/1273084251381960746/1273091728164786319), it should read out the version number:
```
[20:26:03.611] [BoneLibUpdater] BoneLib is in ONLINE mode
[20:26:03.727] [BoneLibUpdater] BoneLib.dll found in Mods folder. Version: 3.0.0
[20:26:11.468] [BoneLibUpdater] BoneLib.dll updated successfully!
```
This is, as I understand it, the situation you are describing (the point at which v3.1.1 was the latest, but the version number in the dll metadata was v3.0.0).

The log I posted in the OP does not read out the version number in order to determine an updated was needed (falsely or otherwise), because it failed to read the dll:
```
[12:11:53.124] [BoneLibUpdater] BoneLib is in ONLINE mode
[12:11:53.132] [BoneLibUpdater] System.BadImageFormatException: Could not load file or assembly 'C:\Program Files\Oculus\Software\Software\stress-level-zero-inc-bonelab\Mods\BoneLib.dll'. An attempt was made to load a program with an incorrect format.
File name: 'C:\Program Files\Oculus\Software\Software\stress-level-zero-inc-bonelab\Mods\BoneLib.dll'
   at System.Reflection.AssemblyName.nGetFileInformation(String s)
   at System.Reflection.AssemblyName.GetAssemblyName(String assemblyFile)
   at BoneLibUpdater.Updater.UpdateMod()
   at BoneLibUpdater.Main.OnPreInitialization()
   at MelonLoader.MelonEvent.<>c.<Invoke>b__1_0(LemonAction x) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 174
   at MelonLoader.MelonEventBase`1.Invoke(Action`1 delegateInvoker) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 143
```
And there is no attempt made to correct the issue.
